GET http://localhost:5000/albums

###

GET http://localhost:5000/albums/5e0250359f3dbf41e8ff47d5

###

POST http://localhost:5000/albums
Content-TYPE: application/json

{
    "name": "Luke mung",
    "location": "philadelphia"
}

###

DELETE  http://localhost:5000/albums/5e1017ef1db1a26897dc6250

###

PATCH http://localhost:5000/albums/5e0250359f3dbf41e8ff47d5
Content-Type: application/json

{
    "name": "mung"
}