GET http://localhost:5000/albums

###

GET http://localhost:5000/albums/5e0250359f3dbf41e8ff47d5

###


GET http://localhost:5000/photos

###

GET http://localhost:5000/photos/Japan-2019

###

POST http://localhost:5000/photos/upload-photos
Content-TYPE: application/json

{
    "albumName": "Luke mung"
}
###

POST http://localhost:5000/layouts/create
Content-TYPE: application/json

{
    "name" : "homepage"
}


###

POST http://localhost:5000/photos
Content-TYPE: application/json

{
    "albumName": "Luke mung"
}

###

DELETE  http://localhost:5000/albums/5e1017ef1db1a26897dc6250

###

DELETE  http://localhost:5000/albums/deleteAlbum/luke-hoang

###

PATCH http://localhost:5000/albums/5e0250359f3dbf41e8ff47d5
Content-Type: application/json

{
    "name": "mung"
}



###

POST http://localhost:5000/users/register
Content-TYPE: application/json

{
    "username": "luke",
    "password": "bamboo!234"
}